<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace Tyhp\Compiler;

/**
 * HTTP GET used by {@see Installer}. Tests inject a fake so PHPUnit never hits GitHub.
 */
interface HttpClient
{
    public function get(string $url, array $headers = []): string;
    public function downloadToFile(string $url, string $destination, array $headers = []): void;
}
//# sourceMappingURL=HttpClient.php.map
