<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace Tyhp\Compiler;

/**
 * Downloads the native Tyhp CLI from GitHub Releases into this package's `native/` dir.
 *
 * Checksum and asset-naming policy matches scripts/release.sh, scripts/install.sh,
 * scripts/install.ps1, and the Story 19.5 IDE installers: SHA-256 via checksums.txt;
 * assets `tyhp-{os}-{arch}` / `-fxdependent`, with `.exe` on Windows.
 */
final class Installer
{
    public const string RELEASE_REPO = 'tyhpproject/tyhp';
    public const string CHECKSUMS_ASSET = 'checksums.txt';
    public const string USER_AGENT = 'tyhp-compiler-package';
    public const string NATIVE_DIR = 'native';
    public const string VERSION_STAMP = 'version';
    private readonly \Tyhp\Compiler\HttpClient $http;
    private readonly \Tyhp\Compiler\Platform $platform;
    public function __construct(private readonly string $packageRoot, ?\Tyhp\Compiler\HttpClient $http = null, ?\Tyhp\Compiler\Platform $platform = null, private readonly ?bool $hasDotNet9 = null, private readonly ?string $packageVersion = null)
    {
        $this->http = ($http ?? new NativeHttpClient());
        $this->platform = ($platform ?? Platform::detect());
    }
    public static function fromPackage(): self
    {
        return new self(\dirname(__DIR__));
    }
    public static function normalizeReleaseTag(string $value): string
    {
        $trimmed = \trim($value);
        if ($trimmed === '') {
            throw new \RuntimeException('Tyhp compiler package version is empty; cannot pin a GitHub release tag.');
        }
        if (($trimmed[0] === 'v') || ($trimmed[0] === 'V')) {
            return $trimmed;
        }
        return 'v' . $trimmed;
    }
    /**
     * Parse GNU `sha256sum` output (`checksums.txt` from scripts/release.sh).
     *
     * @return array<string, string> asset name → lowercase hex SHA-256
     */
    public static function parseChecksumFile(string $contents): array
    {
        $map = [];
        $results = \preg_split('/\r\n|\n|\r/', $contents);
        if ($results === false) {
            throw new \RuntimeException('Checksum file contents could not be split into lines.');
        }
        foreach ($results as $rawLine) {
            $line = \trim($rawLine);
            if (($line === '') || \str_starts_with($line, '#')) {
                continue;
            }
            $match = [];
            if (\preg_match('/^([a-fA-F0-9]{64})\s+\*?(\S+)\s*$/', $line, $match) !== 1) {
                continue;
            }
            $map[$match[2]] = \strtolower($match[1]);
        }
        return $map;
    }
    public function nativeBinaryPath(): string
    {
        return ($this->nativeDir() . \DIRECTORY_SEPARATOR) . $this->platform->binaryFileName();
    }
    public function nativeDir(): string
    {
        return ($this->packageRoot . \DIRECTORY_SEPARATOR) . self::NATIVE_DIR;
    }
    /**
     * True when the on-disk native compiler can be launched (present, non-empty, executable).
     * Does not start a download.
     */
    public function isNativeBinaryAvailable(): bool
    {
        $path = $this->nativeBinaryPath();
        if (!\is_file($path) || !\is_readable($path)) {
            return false;
        }
        if (\filesize($path) === 0) {
            return false;
        }
        if (($this->platform->os !== 'win') && !\is_executable($path)) {
            return false;
        }
        return true;
    }
    /**
     * Pin: GitHub release tag for this Composer package version (compiler MAJOR 805, not runtime 804).
     */
    public function expectedReleaseTag(): string
    {
        $version = ($this->packageVersion ?? $this->readComposerVersion());
        return self::normalizeReleaseTag($version);
    }
    /**
     * Download the pinned native binary. Idempotent: matching binary already present → no-op.
     */
    public function installBinary(): void
    {
        $tag = $this->expectedReleaseTag();
        if ($this->isNativeBinaryAvailable() && $this->installedTagMatches($tag)) {
            return;
        }
        $variant = $this->chooseAssetVariant();
        $assetName = $this->platform->releaseAssetName($variant);
        $headers = $this->githubHeaders();
        $release = $this->fetchReleaseByTag($tag, $headers);
        $assetUrl = $this->requireAssetUrl($release, $assetName, $tag);
        $checksumUrl = $this->requireAssetUrl($release, self::CHECKSUMS_ASSET, $tag);
        $checksumText = $this->http->get($checksumUrl, $headers);
        $checksums = self::parseChecksumFile($checksumText);
        if (!isset($checksums[$assetName])) {
            throw new \RuntimeException(('checksums.txt has no SHA-256 for `' . $assetName) . '`. Refusing to install an unverified binary.');
        }
        $expected = $checksums[$assetName];
        $tmpFile = (((\sys_get_temp_dir() . \DIRECTORY_SEPARATOR) . 'tyhp-compiler-') . \bin2hex(\random_bytes(8)));
        try {
            $this->http->downloadToFile($assetUrl, $tmpFile, $headers);
            if (!\is_file($tmpFile) || (\filesize($tmpFile) === 0)) {
                throw new \RuntimeException("Downloaded artifact `$assetName` is empty.");
            }
            $actual = \hash_file('sha256', $tmpFile);
            if ($actual === false) {
                throw new \RuntimeException("Unable to hash downloaded artifact `$assetName`.");
            }
            if (\strtolower($actual) !== $expected) {
                throw new \RuntimeException("SHA-256 mismatch for `$assetName`: expected $expected, got $actual. " . 'The download may be corrupt or tampered with.');
            }
            $destDir = $this->nativeDir();
            if ((!\is_dir($destDir) && !\mkdir($destDir, 0777, true)) && !\is_dir($destDir)) {
                throw new \RuntimeException("Failed to create $destDir.");
            }
            $dest = $this->nativeBinaryPath();
            $this->replaceFile($tmpFile, $dest);
            $tmpFile = '';
            if ($this->platform->os !== 'win') {
                \chmod($dest, 0755);
            }
            \file_put_contents(($destDir . \DIRECTORY_SEPARATOR) . self::VERSION_STAMP, $tag . "\n");
        } finally {
            if (($tmpFile !== '') && \is_file($tmpFile)) {
                \unlink($tmpFile);
            }
        }
    }
    private function installedTagMatches(string $expectedTag): bool
    {
        $stamp = (($this->nativeDir() . \DIRECTORY_SEPARATOR) . self::VERSION_STAMP);
        if (!\is_file($stamp)) {
            return false;
        }
        $installed = \trim((string) \file_get_contents($stamp));
        if ($installed === '') {
            return false;
        }
        return \strtolower(self::normalizeReleaseTag($installed)) === \strtolower($expectedTag);
    }
    private function chooseAssetVariant(): string
    {
        return $this->detectDotNet9() ? 'framework-dependent' : 'self-contained';
    }
    private function detectDotNet9(): bool
    {
        if ($this->hasDotNet9 !== null) {
            return $this->hasDotNet9;
        }
        $pipes = [];
        try {
            $proc = \proc_open(['dotnet', '--list-runtimes'], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, null, null, ['bypass_shell' => true]);
        } catch (\Throwable) {
            return false;
        }
        if (!\is_resource($proc)) {
            return false;
        }
        $stdout = \stream_get_contents($pipes[1]);
        \fclose($pipes[1]);
        \fclose($pipes[2]);
        \proc_close($proc);
        return \is_string($stdout) && (\preg_match('/Microsoft\.NETCore\.App 9\./', $stdout) === 1);
    }
    private function fetchReleaseByTag(string $tag, array $headers): array
    {
        $url = ((('https://api.github.com/repos/' . self::RELEASE_REPO) . '/releases/tags/') . \rawurlencode($tag));
        $body = $this->http->get($url, $headers);
        try {
            $release = \Tyhp\Generic::bind(\Tyhp\Json::decode(...), \Tyhp\Type::struct('Tyhp\\Compiler\\GitHubRelease', ['tag_name' => \Tyhp\Type::string(), 'assets' => \Tyhp\Type::generic('array', new \Tyhp\NamedType('TValue', \Tyhp\Type::struct('Tyhp\\Compiler\\GitHubReleaseAsset', ['name' => \Tyhp\Type::string(), 'browser_download_url' => \Tyhp\Type::string()], ['name', 'browser_download_url'])))], ['tag_name', 'assets']))($body);
            if ($release['tag_name'] === '') {
                throw new \RuntimeException(("GitHub release tag `$tag` was not found on " . self::RELEASE_REPO) . '.');
            }
            return $release;
        } catch (\JsonException $e) {
            throw new \RuntimeException('GitHub release JSON could not be parsed: ' . $e->getMessage(), 0, $e);
        } catch (\Tyhp\Exceptions\IncompatibleTypeException) {
            throw $this->releaseNotFound($tag, $body);
        }
    }
    private function releaseNotFound(string $tag, string $body): \RuntimeException
    {
        $error = ['message' => ''];
        $apiMessage = null;
        if (\Tyhp\Generic::bind(\Tyhp\Json::tryDecode(...), \Tyhp\Type::struct('Tyhp\\Compiler\\GitHubApiError', ['message' => \Tyhp\Type::string()], ['message']))($body, $error) && ($error['message'] !== '')) {
            $apiMessage = $error['message'];
        }
        return new \RuntimeException((("GitHub release tag `$tag` was not found on " . self::RELEASE_REPO) . (($apiMessage !== null) ? " ($apiMessage)" : '')) . '.');
    }
    private function requireAssetUrl(array $release, string $assetName, string $tag): string
    {
        foreach ($release['assets'] as $asset) {
            $typedAsset = $asset;
            if (($typedAsset['name'] === $assetName) && ($typedAsset['browser_download_url'] !== '')) {
                return $typedAsset['browser_download_url'];
            }
        }
        throw new \RuntimeException("GitHub release $tag has no asset named `$assetName`.");
    }
    private function githubHeaders(): array
    {
        $headers = ['User-Agent' => self::USER_AGENT, 'Accept' => 'application/vnd.github+json'];
        $token = \getenv('GITHUB_TOKEN');
        if (($token === false) || ($token === '')) {
            $token = \getenv('GH_TOKEN');
        }
        if (\is_string($token) && ($token !== '')) {
            $headers['Authorization'] = ('token ' . $token);
        }
        return $headers;
    }
    private function readComposerVersion(): string
    {
        $path = (($this->packageRoot . \DIRECTORY_SEPARATOR) . 'composer.json');
        if (!\is_file($path)) {
            throw new \RuntimeException("composer.json not found at $path; cannot pin the compiler release tag.");
        }
        try {
            $manifest = \Tyhp\Generic::bind(\Tyhp\Json::decode(...), \Tyhp\Type::struct('Tyhp\\Compiler\\ComposerManifest', ['version' => \Tyhp\Type::string()], ['version']))((string) \file_get_contents($path));
            if (\trim($manifest['version']) === '') {
                throw new \RuntimeException("composer.json at $path has no version; cannot pin the compiler release tag.");
            }
            return $manifest['version'];
        } catch (\JsonException $e) {
            throw new \RuntimeException("composer.json at $path could not be parsed: " . $e->getMessage(), 0, $e);
        } catch (\Tyhp\Exceptions\IncompatibleTypeException $e) {
            throw new \RuntimeException("composer.json at $path has no version; cannot pin the compiler release tag.", 0, $e);
        }
    }
    private function replaceFile(string $from, string $to): void
    {
        if (\is_file($to)) {
            \unlink($to);
        }
        if (!\rename($from, $to)) {
            if (!\copy($from, $to)) {
                throw new \RuntimeException("Failed to place native binary at $to.");
            }
            \unlink($from);
        }
    }
}
//# sourceMappingURL=Installer.php.map
