<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace Tyhp\Compiler;

final class NativeHttpClient implements HttpClient
{
    public function get(string $url, array $headers = []): string
    {
        return $this->curl($url, $headers, null);
    }
    public function downloadToFile(string $url, string $destination, array $headers = []): void
    {
        $this->curl($url, $headers, $destination);
    }
    private function curl(string $url, array $headers, ?string $destination): string
    {
        if (!\function_exists('curl_init')) {
            throw new \RuntimeException('The curl PHP extension is required to download the Tyhp compiler binary.');
        }
        $handle = \curl_init($url);
        if ($handle === false) {
            throw new \RuntimeException("Failed to initialize cURL for $url.");
        }
        $headerLines = [];
        foreach ($headers as $name => $value) {
            $headerLines[] = (($name . ': ') . $value);
        }
        $file = null;
        $options = [\CURLOPT_FOLLOWLOCATION => true, \CURLOPT_HTTPHEADER => $headerLines, \CURLOPT_TIMEOUT => 120, \CURLOPT_FAILONERROR => false];
        if ($destination !== null) {
            $opened = \fopen($destination, 'wb');
            if ($opened === false) {
                unset($handle);
                throw new \RuntimeException("Failed to open $destination for writing.");
            }
            $file = $opened;
            $options[\CURLOPT_FILE] = $file;
        } else {
            $options[\CURLOPT_RETURNTRANSFER] = true;
        }
        \curl_setopt_array($handle, $options);
        $result = \curl_exec($handle);
        $status = (int) \curl_getinfo($handle, \CURLINFO_HTTP_CODE);
        $error = \curl_error($handle);
        if ($file !== null) {
            \fclose($file);
            $file = null;
        }
        unset($handle);
        if ($result === false) {
            $this->deleteIfExists($destination);
            throw new \RuntimeException("Download failed for $url: $error");
        }
        if (($status < 200) || ($status >= 300)) {
            $this->deleteIfExists($destination);
            $snippet = (\is_string($result) ? \substr($result, 0, 200) : '');
            throw new \RuntimeException("HTTP $status from $url" . (($snippet !== '') ? ": $snippet" : '.'));
        }
        return \is_string($result) ? $result : '';
    }
    private function deleteIfExists(?string $path): void
    {
        if (($path !== null) && \is_file($path)) {
            \unlink($path);
        }
    }
}
//# sourceMappingURL=NativeHttpClient.php.map
