<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace Tyhp\Compiler;

/**
 * Composer `"bin"` entry: intercept `--install-binary`, otherwise exec the native CLI.
 */
final class Shim
{
    private mixed $stderr;
    /**
     * @param resource|null $stderr
     */
    public function __construct(private readonly ?\Tyhp\Compiler\Installer $installer = null, mixed $stderr = null)
    {
        $this->stderr = ($stderr ?? \STDERR);
    }
    /**
     * @param list<string> $argv
     */
    public function run(array $argv): int
    {
        $installer = ($this->installer ?? Installer::fromPackage());
        $args = \array_slice($argv, 1);
        if (\in_array('--install-binary', $args, true)) {
            try {
                $installer->installBinary();
            } catch (\Throwable $e) {
                \fwrite($this->stderr, $e->getMessage() . "\n");
                return 1;
            }
            return 0;
        }
        if (!$installer->isNativeBinaryAvailable()) {
            \fwrite($this->stderr, ("The Tyhp native compiler binary is not available.\n" . "Run `vendor/bin/tyhp --install-binary` to download it.\n") . "This can happen if `composer install` was run with `--no-scripts`, or if that post-install step failed.\n");
            return 1;
        }
        return $this->forward($installer->nativeBinaryPath(), $args);
    }
    /**
     * @param list<string> $args
     */
    private function forward(string $binary, array $args): int
    {
        $command = \array_merge([$binary], $args);
        $proc = \proc_open($command, [0 => \STDIN, 1 => \STDOUT, 2 => \STDERR], $pipes, null, null, ['bypass_shell' => true]);
        if (!\is_resource($proc)) {
            \fwrite($this->stderr, "Failed to launch the Tyhp native compiler at $binary.\n");
            return 1;
        }
        $status = \proc_close($proc);
        return ($status === -1) ? 1 : $status;
    }
}
//# sourceMappingURL=Shim.php.map
